runner: HIRLRunner

pipeline:
  name: "HIRL"
  num_cluster: [30000,10000,5000]
  num_neg_path: 100
  train_emb: "vit_cls"
  num_mlp_layer: 5
  activation: "relu"

T: 0.2
cluster_warmup_epoch: 40
iter_wise_assignment: False

base_runner: MoCoV3Runner

arch: vit_base

batch_size: 32 
epochs: 400
accum_iter: 1

model: "mocov3_vit_base_single_crop"
local_views_sum: True
moco_momentum: 0.99
moco_momentum_cosine: True

multi_crop: False
global_crops_number: 2
global_crops_scale: [0.08, 1.0] 
local_crops_number: 0
local_crops_scale: [0.0, 0.08] 

optimizer: "adamw"
lr: 1.5e-4
min_lr: 0.
momentum: 0.9
weight_decay: 0.1
warmup_epochs: 40

data_path: "./datasets/Imagenet1K/ILSVRC/Data/CLS-LOC/"

output_dir: "./experiments/pretrain/hirl/mocov3_vit_base_200eps/"

autoresume: True
resume: null
seed: 0
num_workers: 10

log_interval: 10
save_interval: 10
use_fp16: True

dist_url: "env://"