runner: HIRLRunner

pipeline:
  name: "HIRL"
  num_cluster: [30000,10000,1000]
  num_neg_path: 1000
  train_emb: "cnn"
  num_mlp_layer: 2
  activation: "relu"

T: 0.1
cluster_warmup_epoch: 80
iter_wise_assignment: True

base_runner: SwAVRunner

arch: resnet50

batch_size: 128
epochs: 800
accum_iter: 1

model: "swav_resnet50_multi_crop"

queue_length: 0 

multi_crop: True
nmb_crops: [2, 6]
size_crops: [224, 96]
min_scale_crops: [0.14, 0.05]
max_scale_crops: [1.0, 0.14]
color_scale: 1.0
color_first: True

optimizer: lars
lr: 0.3 
min_lr: 0.0048
start_lr: 0.3

freeze_proto_iter: 313

momentum: 0.9
weight_decay: 0.000001
warmup_epochs: 10

data_path: "./datasets/Imagenet1K/ILSVRC/Data/CLS-LOC/"

output_dir: "./experiments/pretrain/hirl/swav_resnet50_800eps/"

autoresume: True
resume: null
seed: 0
num_workers: 10

log_interval: 10
save_interval: 10
use_fp16: True

dist_url: "env://"