runner: LinclsRunner

arch: resnet50
batch_size: 32 
epochs: 100
accum_iter: 1

patch_size: 16
window_size: 7
drop_path_rate: 0.1

lr: 30.0
min_lr: 0
warmup_epochs: 0


optimizer:
  name: "SGD"
  params:
    weight_decay: 0.
    momentum: 0.9

schedule: [60, 80]


trunc_normal: True
use_mean_pooling: True
dist_eval: True

data_path: "./datasets/Imagenet1K/ILSVRC/Data/CLS-LOC/"

output_dir: "./experiments/downstream/lincls/mocov2/mocov2_resnet50_200eps/"


autoresume: True
pretrained: ""
backbone_prefix: "backbone"
resume: null
seed: 0
num_workers: 10
num_classes: 1000

log_interval: 10
save_interval: 10
use_fp16: False

dist_url: "env://"
