runner: SimSiamRunner

arch: resnet50

batch_size: 32
epochs: 200
accum_iter: 1

model: "simsiam_resnet50"
dim: 2048
pred_dim: 512

fix_pred_lr: True # simsiam specific trick

multi_crop: False
nmb_crops: [2,]
size_crops: [224,]
min_scale_crops: [0.2, ]
max_scale_crops: [1.0, ]

optimizer: lars
lr: 0.05
min_lr: 0.
momentum: 0.9
weight_decay: 1.0e-4

data_path: "./datasets/Imagenet1K/ILSVRC/Data/CLS-LOC/"

output_dir: "./experiments/pretrain/baseline/simsiam_resnet50_200eps"

autoresume: True
resume: null
seed: 0
num_workers: 10

log_interval: 10
save_interval: 10

use_fp16: True

dist_url: "env://"