runner: LinclsRunner

arch: vit_base
arch_kwargs:
  use_abs_pos_emb: False
  use_shared_rel_pos_bias: True
  init_values: 0.1

batch_size: 128 
epochs: 100
accum_iter: 1

patch_size: 16
window_size: 7
drop_path_rate: 0.0
n_last_blocks: 1 

lr: 4.0e-3
min_lr: 0
warmup_epochs: 0

optimizer:
  name: "SGD"
  params:
    weight_decay: 0.
    momentum: 0.9

cos: True
warmup_epochs: 0


trunc_normal: True
use_mean_pooling: False
dist_eval: True

data_path: "./datasets/Imagenet1K/ILSVRC/Data/CLS-LOC/"

output_dir: "./experiments/downstream/lincls/beit/hirl_beit_base_400eps/"


autoresume: True
pretrained: ""
backbone_prefix: "model.backbone"
resume: null
seed: 0
num_workers: 10
num_classes: 1000

log_interval: 10
save_interval: 10
use_fp16: False

dist_url: "env://"
